name: Python Flask Application CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Run Flask application
      run: |
        source venv/bin/activate
        FLASK_APP=app.py flask run --host=0.0.0.0 --port=8081 &
        sleep 5

    - name: Test application
      run: |
        curl --fail http://localhost:8081/stock?apikey=test&ticker=AAPL || exit 1
